apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: wededo4644/flask-app:5fc1c2847ce0c5215b936747b4f0864963f2acfa
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
