apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
      nodePort: 31000
